### ISSUE TITLE
Multi Dimensional LSTM return size

### ISSUE THREAD

**Issue by adithyakanchan** [philipperemy/tensorflow-multi-dimensional-lstm#1]
In the comment section of "**def multi_dimensional_rnn_while_loop(rnn_size, input_data, sh, dims=None, scope_n="layer1"):**" funtion you have mensioned return tensor shape is **[batch,h/sh[0],w/sh[1],channels x sh[0] x sh[1]]**
but Actually when you are returning from above mensioned function your return tensor shape is 
**[batch,h/sh[0],w/sh[1],rnn_size]**
Can you please explain why is it so?

**Comment by philipperemy** [comment]
Sorry for the last reply.

sh is a parameter that squeezes the grid. Most of the time you won't use it and you should set it to (1, 1).

You are right. I think I made a mistake in the comment.

The input shape is something like `[batch_size, h, w, channels]`.

The return shape is well `[batch_size, h, w, rnn_size]`.

(If we set sh to 1,1).

**Comment by philipperemy** [comment]
(I've updated the comment)
